image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

build:
  stage: build
  script:
    - apk add --update openvpn openssh-client sshpass
    - openvpn --config vpn-users.ovpn --auth-user-pass auth-users.txt & 
    - sshpass -p "kapusta421" scp -o StrictHostKeyChecking=no -r backend wpadmin@przedszkole.projektstudencki.pl:/home/wpadmin