image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

build:
  stage: build
  script:
    - apk add --update nodejs npm maven openjdk11
    - cd frontend/wirtualneprzedszkole
    - npm i --save @fortawesome/fontawesome-svg-core
    - npm i --save @fortawesome/free-solid-svg-icons
    - npm install -f
    - npm run build
    - cd ../../backend
    - mvn clean install

test:
  stage: test
  script:
    - cd frontend/wirtualneprzedszkole
    - npm run test
    - cd ../../backend
    - mvn test

deploy:
  stage: deploy
  only:
    - master
  script:
    - echo Hi
