image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

build:
  stage: build
  script:
    - apk add --update openvpn openssh-client
    - openvpn --config vpn-users.ovpn --askpass auth-users.txt && scp -o StrictHostKeyChecking=no -r ./ wpadmin@przedszkole.projektstudencki.pl:/home/wpadmin