image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

build:
  stage: build
  only:
    - master
  script:
    - apk add --update nodejs npm maven openjdk11
    - cd frontend/wirtualneprzedszkole
    - npm i --save @fortawesome/fontawesome-svg-core
    - npm i --save @fortawesome/free-solid-svg-icons
    - npm install -f
    - npm run build
    - cd ../../backend
    - mvn clean install

test:
  stage: test
  script:
    - apk add --update nodejs npm maven openjdk11
    - cd frontend/wirtualneprzedszkole
    - npm i react-scripts 
    - npm i --save @fortawesome/fontawesome-svg-core
    - npm i --save @fortawesome/free-solid-svg-icons
    - cd ../../backend
    - mvn test

deploy_job:
  stage: deploy
  script:
    - make deploy
  when: manual

deploy:
  stage: deploy
  only:
    - master
  script:
    - apk add --update openvpn openssh-client sshpass
    - openvpn --config vpn-users.ovpn --auth-user-pass auth-users.txt & 
    - sleep 15
    - pwd=$(pwd)
    - sshpass -p "kapusta421" scp -o StrictHostKeyChecking=no -r $pwd wpadmin@przedszkole.projektstudencki.pl:/home/wpadmin
